language: go

go_import_path: go.spiff.io/go-fex
go:
  - '1.10.x'
  - '1.11.x'

script:
  - env GO111MODULE=on go build ./cmd/fex
  - env GO111MODULE=on go test -v -coverprofile=coverage.txt -covermode=atomic ./internal/fex

after_success:
  - bash <(curl -s https://codecov.io/bash)
